[general]
static = yes
writeprotect = no
clearglobalvars = no

[globals]
RECORDING_DIR=/var/spool/asterisk/monitor

[callcenter]
; Ringtone personalizado (tono de llamada para el que llama)
exten => _1XXX,1,Set(RECORDING_FILE=${RECORDING_DIR}/${UNIQUEID}-${CALLERID(num)}-${EXTEN}.wav)
 same => n,MixMonitor(${RECORDING_FILE})
 same => n,NoOp(Grabando: ${RECORDING_FILE})
 same => n,Ringing()
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => _2XXX,1,Set(RECORDING_FILE=${RECORDING_DIR}/${UNIQUEID}-${CALLERID(num)}-${EXTEN}.wav)
 same => n,MixMonitor(${RECORDING_FILE})
 same => n,Ringing()
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => _3XXX,1,Set(RECORDING_FILE=${RECORDING_DIR}/${UNIQUEID}-${CALLERID(num)}-${EXTEN}.wav)
 same => n,MixMonitor(${RECORDING_FILE})
 same => n,Ringing()
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => 8000,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

[supervisors]
include => callcenter

[admins]
include => callcenter
