[global]
type = global
default_realm = localhost
endpoint_identifier_order = ip,user,anonymous

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[transport-tls]
type = transport
protocol = tls
bind = 0.0.0.0:5061
cert_file = /etc/asterisk/keys/asterisk.pem
priv_key_file = /etc/asterisk/keys/asterisk.key
method = tlsv1_2
verify_server = no
verify_client = no

[transport-ws]
type = transport
protocol = ws
bind = 0.0.0.0:8088

[ext-base](!)
type = endpoint
context = callcenter
disallow = all
allow = ulaw
allow = alaw
allow = g729
allow = opus
webrtc = yes
transport = transport-ws
identify_by = username

[auth-base](!)
type = auth
auth_type = userpass

[aor-base](!)
type = aor
max_contacts = 1

[3003](ext-base)
auth = 3003-auth
aors = 3003-aor
callerid = "Agente Uno" <3003>

[3003-auth](auth-base)
username = 3003
password = sip3003pass

[3003-aor](aor-base)

[3004](ext-base)
auth = 3004-auth
aors = 3004-aor
callerid = "Agente Dos" <3004>

[3004-auth](auth-base)
username = 3004
password = sip3004pass

[3004-aor](aor-base)
