apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: callcenter
    user: callcenter
    secureJsonData:
      password: CallCenter2024!
    jsonData:
      sslmode: disable
      postgresVersion: 1500
