[global]
type = global
endpoint_identifier_order = ip,user,anonymous

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[transport-tls]
type = transport
protocol = tls
bind = 0.0.0.0:5061
cert_file = /etc/asterisk/keys/asterisk.pem
priv_key_file = /etc/asterisk/keys/asterisk.key
method = tlsv1_2
verify_server = no
verify_client = no

[transport-ws]
type = transport
protocol = ws
bind = 0.0.0.0:8089

[1001]
type = endpoint
context = callcenter
disallow = all
allow = ulaw
allow = alaw
allow = g729
auth = 1001-auth
aors = 1001
callerid = "Agente 1" <1001>
webrtc = yes
transport = transport-ws
identify_by = username

[1001-auth]
type = auth
auth_type = userpass
password = sip1001pass
username = 1001

[1001]
type = aor
max_contacts = 1
qualify_frequency = 30

[1002]
type = endpoint
context = callcenter
disallow = all
allow = ulaw
allow = alaw
allow = g729
auth = 1002-auth
aors = 1002
callerid = "Agente 2" <1002>
webrtc = yes
transport = transport-ws
identify_by = username

[1002-auth]
type = auth
auth_type = userpass
password = sip1002pass
username = 1002

[1002]
type = aor
max_contacts = 1
qualify_frequency = 30

[2001]
type = endpoint
context = supervisors
disallow = all
allow = ulaw
allow = alaw
allow = g729
auth = 2001-auth
aors = 2001
callerid = "Supervisor 1" <2001>
webrtc = yes
transport = transport-ws
identify_by = username

[2001-auth]
type = auth
auth_type = userpass
password = sip2001pass
username = 2001

[2001]
type = aor
max_contacts = 1
qualify_frequency = 30

[3001]
type = endpoint
context = admins
disallow = all
allow = ulaw
allow = alaw
allow = g729
auth = 3001-auth
aors = 3001
callerid = "Admin 1" <3001>
webrtc = yes
transport = transport-ws
identify_by = username

[3001-auth]
type = auth
auth_type = userpass
password = sip3001pass
username = 3001

[3001]
type = aor
max_contacts = 1
qualify_frequency = 30
